extends Camera2D

@onready var scoreLabel = $CanvasLayer/Control/VBoxContainer/HBoxContainer/ScoreValue
@onready var timeLabel = $CanvasLayer/Control/VBoxContainer/HBoxContainer2/TimeValue

# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta: float) -> void:
	scoreLabel.text = str(GLOBAL.points)
	timeLabel.text = str(GLOBAL.time)
