extends Control

@onready var score = $VBoxContainer3/VBoxContainer2/ScoreValue
@onready var time = $VBoxContainer3/VBoxContainer/TimeValue

# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	score.text = str(GLOBAL.points)
	time.text = str(GLOBAL.time)
	GLOBAL.resetGame()


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta: float) -> void:
	pass




func _on_play_again_button_pressed() -> void:
	get_parent().get_parent().laodGrid()


func _on_home_pressed() -> void:
	get_parent().get_parent().loadStartMenu()
